version: '3.8' # Specifies the Compose file version

services:
  # Define the PostgreSQL database service
  postgres_db:
    image: postgres:15 # Use the official PostgreSQL image, version 15
    container_name: innvoice_postgres_db # Give the container a specific name
    environment:
      POSTGRES_USER: ${DB_USER} # Database username (uses .env or default)
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Database password (uses .env or default)
      POSTGRES_DB: ${DB_NAME} # Database name (uses .env or default)
    ports:
      - "${DB_PORT}:5432" # Map host port (uses .env or default 5432) to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data using a Docker volume
    restart: unless-stopped # Restart the container if it stops, unless manually stopped

volumes:
  # Define the Docker volume for data persistence
  postgres_data:
    driver: local